### PR TITLE
Add Cassandra 3.11.11

### LINKED ISSUE #55: Make heap memory for the Management API configurable
I set the JVM heap with -Xms128m and -Xmx128m - we can probably set both lower. Also setting Netty to use less memory would be good.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-157) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-157
┆Priority: Medium

### PR DESCRIPTION
**Pull request by emerkle826**
This should fix #55, as well as update the Cassandra image to 3.11.11

### CODE REVIEW

**Comment by emerkle826** [comment]
@jsanda If you get to test out the images with these changes and have no issues, let me know.

**Comment by jsanda** [comment]
Sure thing. I probably won't get to it today, but I will report back my results when I do.

**Comment by jsanda** [comment]
I have done some initial testing in this branch https://github.com/jsanda/k8ssandra-operator/tree/k8ssandracluster-status. So far the changes look good.

**Review by nastra — APPROVED** [review]
LGTM

**Pull request merged**
