### PR TITLE
add mtab symlink

### LINKED ISSUE #181: K8SSAND-1361 ⁃ add /etc/mtab to /proc/mounts symlink to account for the containerd runtime collectd disk monitor
Hi, 

There is a change when it comes to using the containerd compare to moby runtime as [containerd does not create the default symlinks](https://github.com/containerd/containerd/issues/2419)

collectd:df plugin assumes that /etc/mtab is populated accordingly to the collectd logs inside the k8ssadra managed deployment which breaks the disk stats exporter as no mounts are detected

```text
[2022-03-24 01:05:59] setmntent (/etc/mtab): No such file or directory
[2022-03-24 01:05:59] df plugin: cu_mount_getlist failed.
```

Does this makes sense to update the Dockerfile and add a symlink `/etc/mtab -> /proc/mounts` so C* disks can be monitored?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1361) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1361
┆priority: Medium

### PR DESCRIPTION
**Pull request by andrey-dubnik**
Fixes #181

### CODE REVIEW

**Comment by andrey-dubnik** [comment]
@emerkle826 some tests are failing but it does not look they are failing because of the changes made in this PR

**Comment by emerkle826** [comment]
I've run the 4.0 tests locally and they pass. Re-running them now on GHA, but I agree that the failure is not due to the changes. The DSE failures are due to not having access to a proprietary repo, so unfortunately those tests will always fail.

**Comment by emerkle826** [comment]
The same test failed again, but I still don't think it has anything to do with the change. I'll merge this and try to see if I can isolate why GHA is failing.

**Comment by emerkle826** [comment]
@andrey-dubnik have you signed the CLA agreement at https://cla.datastax.com/

**Comment by andrey-dubnik** [comment]
> @andrey-dubnik have you signed the CLA agreement at https://cla.datastax.com/

Yes, I did

**Comment by bradfordcp** [comment]
Thank you for the PR @andrey-dubnik! It's great to count you as a contributor.

**Pull request merged**
