### PR TITLE
Add OpenAPI client generation

### LINKED ISSUE #323: Generate Java client for OpenAPI spec
Generating a Java client based on the Management API spec will allow other projects to interact with Management API much easier (as opposed to downstream projects having to maintain their own REST client implementations that work with this project's API).

```[tasklist]
### DoD
- [ ] Add build task to generate Java client code that implements the[OpenAPI spec
- [ ] Client code should be built and published to a Maven artifactory repository during Management API release jobs
- [ ] Annotations on existing API endpoint implementations should be updated, as necessary
```

As a clarification for the last DoD item above, some of the endpoints are not currently annotated with a response `schema`. For example, [listKeyspaces](https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/master/management-api-server/src/main/java/com/datastax/mgmtapi/resources/KeyspaceOpsResources.java#L234-L248) annotates the Response as JSON, but does not specify a `schema` attribute. This causes the client generation to create a method that has a `Void` return type, which will clearly not work for code using the client to retrieve a list of keyspaces. For these methods, adding the `schema` attribute will not change the implementation, so it won't affect existing Management API consumers. It only changes the OpenAPI spec that is generated, which will alter the client code generated.

### PR DESCRIPTION
**Pull request by emerkle826**
This PR does 2 things:
1. Renames the Maven artifact groupId from `com.datastax` to `io.k8ssandra`
2. Creates a workflow_dispatch GHA to on-demand build the OpenAPI Java client and publish it to Datasatx Artifactory

Fixes #323

### CODE REVIEW

**Review by Miles-Garnsey — APPROVED** [review]
I've taken a quick glance, it all looks good to me in theory! 

Issue: I couldn't see a release when I searched in artifactory, have you confirmed that this works by running the mvn deploy command locally? I don't have the credentials, so my ability to test this is a bit limited.

Suggestion: Also, when I look at the other PR you have open, it skips the openAPI build in the docker files. Should those changes be a part of this PR instead? The docs should probably also be in this one. 

Issue: Is there a changelog update that needs to happen here too?

**Comment by emerkle826** [comment]
> Issue: I couldn't see a release when I searched in artifactory, have you confirmed that this works by running the mvn deploy command locally? I don't have the credentials, so my ability to test this is a bit limited.

I haven't tried it manually, so I will.

**Comment by emerkle826** [comment]
> Suggestion: Also, when I look at the other PR you have open, it skips the openAPI build in the docker files. Should those changes be a part of this PR instead? The docs should probably also be in this one.

The Dockerfile changes probably should be in here. It's not critical as even if the Dockerfiles generate the client code, it's not included in the final image. I disabled the generation in there to trim out something else that doesn't need to happen, but it isn't much of a time or space waster in the grand scheme of things.

I will move that in here though and I will move/add the documentation updates to this one as well.

**Comment by emerkle826** [comment]
> Issue: Is there a changelog update that needs to happen here too?

Yep, that's why we have reviews :smile:

**Comment by emerkle826** [comment]
> Issue: I couldn't see a release when I searched in artifactory, have you confirmed that this works by running the mvn deploy command locally? I don't have the credentials, so my ability to test this is a bit limited.

@Miles-Garnsey I have successfully published a version of the client based on this PR and it works. I have updated the README [here](https://github.com/k8ssandra/management-api-for-apache-cassandra/pull/324/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R430-R477) to show how to add it to a project.

**Comment by emerkle826** [comment]
@Miles-Garnsey @adejanovski I'm going to go ahead and merge this. The core of what the PR needs to do is publish the client. It can do that with an on-demand workflow, and it will do that on release. When we complete discussions on if/where to publish other artifacts, we can easily PR that work in as well.

**Pull request merged**
