### PR TITLE
Update ByteBuddy to 1.12.19

### PR DESCRIPTION
**Pull request by burmanm**
Updates ByteBuddy to 1.12.19. Started fine at least with Cassandra 4.0.6

### CODE REVIEW

**Comment by emerkle826** [comment]
@burmanm Looks like the integration tests mostly failed. Can you try to restart them to see if they start to pass? Briefly looking at the logs, it looks like the test timed out waiting for Cassandra to become ready, but the Cassandra log dumps seem to show Cassandra is ready, however the Management API socket may not be. Not sure. Were you able to run any of the tests locally?

**Comment by emerkle826** [comment]
You can run a specific integration test like this:
```sh
mvn verify -Dit.test=LifecycleIT -DfailIfNoTests=false -Drun40tests
```

**Comment by burmanm** [comment]
None of the tests work on my machine, so I can't say. All I get is spam of [WARNING] We have a duplicate com/datastax/dse/protocol/internal/DseProtocolConstants$Opcode.class

etc

And then a failure of random something before tests even really start.

**Comment by burmanm** [comment]
Okay, that was solved (partly - there's still maven warnings) updating all the super-old maven-shade plugin versions.

**Comment by emerkle826** [comment]
I can try to run one locally. It may just be that the tests in general need some work with this update, but the images are fine.

**Comment by burmanm** [comment]
But I have no idea why we have these:

```
Status 409: {"message":"Conflict. The container name \"/mgmtapi\" is already in use by container \"3dfe7a1a042e145ea036602d128b203b21abd1102a31dd9cf351e20c975fba7a\". You have to remove (or rename) that container to be able to reuse that name."}
```

**Comment by emerkle826** [comment]
> But I have no idea why we have these:
> 
> ```
> Status 409: {"message":"Conflict. The container name \"/mgmtapi\" is already in use by container \"3dfe7a1a042e145ea036602d128b203b21abd1102a31dd9cf351e20c975fba7a\". You have to remove (or rename) that container to be able to reuse that name."}
> ```

That is likely due to running the test locally and them not completing successfully. The test will try to build a Docker image and then run a container named "mgmtapi" using the built image. The tests should clean up after themselves, but I guess there might be some cases where the cleanup code doesn't run and the container remains afterwards.

If you manually delete the container, you shouldn't have that error again unless you run into the same situation.

**Comment by burmanm** [comment]
#238 solves this also..

**Pull request closed without merging**
