### PR TITLE
Add CDC Agnet to DSE images

### LINKED ISSUE #217: K8SSAND-1854 ⁃ Add CDC Agent to DSE image
The latest Management API images for DSE do not include the CDC agent

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1854) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1854
┆priority: Medium

### PR DESCRIPTION
**Pull request by emerkle826**
- Update CDC Agent to v 2.2.2
 - Add DSE 6.8.31

Fixes #217

### CODE REVIEW

**Review by Miles-Garnsey — APPROVED** [review]
As discussed, I'm not 100% certain if this change works because we need additional changes in k8ssandra-operator to confirm. 

However, I think it is worth merging now and we'll make corrections as required, I don't think it breaks anything in any event.

**Comment by emerkle826** [comment]
@Miles-Garnsey I have updated this one to create symlinks for the MAAC agent jarfile as well as the server jarfile. This should allow us to address the agent ordering issues in [cass-operator](https://github.com/k8ssandra/cass-operator/issues/476) in a more generic way and not have to determine which server version is running to compute the agent jarfile names.

**Comment by Miles-Garnsey** [comment]
@emerkle826 looks like there are failing tests... Can you have a look at those and also do a manual test with k8ssandra-operator? I'll approve as soon as we confirm that it fixes the issues we saw there.

**Comment by emerkle826** [comment]
@Miles-Garnsey I have some fixes locally that I'm still testing for those test failures. I'll tag you again when I have them pushed.

**Comment by emerkle826** [comment]
@Miles-Garnsey If you could take another pass, I'd appreciate it. I have tested the DSE image with k8ssandra-operator locally and, as long as I edit the `cassandra-env.sh` file to fix the JVM_OPTS bits that should be covered in https://github.com/k8ssandra/cass-operator/issues/476, it works fine.

**Comment by Miles-Garnsey** [comment]
Discussed offline and approved.

**Pull request merged**
