### PR TITLE
Bump to latest RC2 release of C*

### PR DESCRIPTION
**Pull request by jdonenine**
CI Run: https://github.com/k8ssandra/management-api-for-apache-cassandra/runs/2955678815

### CODE REVIEW

**Comment by jdonenine** [comment]
@emerkle826 is there anything else that needs to be bumped that I missed? I went based off what you previously did for RC1.

**Comment by emerkle826** [comment]
> @emerkle826 is there anything else that needs to be bumped that I missed? I went based off what you previously did for RC1.

As long as it compiles and builds, that should be it. The only other thing you have to wait for is the DockerHub images to be published, and it looks like they have been:

https://hub.docker.com/_/cassandra?tab=tags&page=1&ordering=last_updated

**Review by emerkle826 — APPROVED** [review]

**Comment by emerkle826** [comment]
@jdonenine I'm re-running the CI jobs to see if it will pick up the base RC2 image from dockerhub. It looks like it picked up RC1 in the output of the integration tests.

**Comment by emerkle826** [comment]
It picked up RC2. If the tests pass, we can merge this.

**Comment by jdonenine** [comment]
> It picked up RC2. If the tests pass, we can merge this.

Nice, thanks @emerkle826 ill check back on the CI later this morning and if it's still green I'll merge and get back to you about how to release.

**Pull request merged**
